### PR TITLE
Added autobanning and stuff

### PR DESCRIPTION
**Pull request by vlad-s**
Autobanning! *Yes!* When banning BradPitt is no longer a hassle.

Functions:
---
- kicking one or more users with the possibility of adding a reason (reason is separated by a semicolon)
- banning one or more users by nick *or* ident
- autobanning a user - even if a ban is manually unset for a user, his rejoin encounters a kick and ban
- clearing the bans - unbanning everyone in the auto ban list
- unbanning - we don't want to clear the whole list of auto bans for a single user
- listing the bans

Examples
---
- Kicking a user
  - bot, kick user1
  - bot, kick user1; reason
- Kicking multiple users
  - bot, kick user1 user2
  - bot, kick user1 user2; reason
- Banning a user
  - bot, ban user1
  - bot, ban *!*@*ident*
- Banning multiple users
  - bot, ban user1 *!aa@bb
- Unbanning
  - bot, unban user1
- Autobanning
  - bot, autoban user1
- Clearing auto ban list
  - bot, clear bans
- Printing the ban list
  - bot, list bans

### CODE REVIEW

**Comment by Mechazawa** [comment]
Requesting feedback from @Nyubis, @clsr and @codyharrington before I pull and reload the bot.

**Comment by Mechazawa** [comment]
It looks good to me tho.

**Comment by Nyubis** [comment]
This ban command has a conflicting syntax with the command from https://github.com/gentoomen/bhottu/blob/master/modules/bantimer.py

**Comment by codyharrington** [comment]
@Nyubis Yeah. We could merge these two modules. In any case, kudos to @pruf @vlad-s for this.

**Comment by Mechazawa** [comment]
@Nyubis How does it have a clonflicting syntax?

**Pull request merged**
